apiVersion: apps/v1
kind: Deployment
metadata:
  name: goazureporjectapi
spec:
  replicas: 3
  selector:
    matchLabels:
      name: goazureporjectapi
  template:
    metadata:
      labels:
        name: goazureporjectapi
    spec:
      containers:
      - image: kiranbabycontainerreg.azurecr.io/kiranbabycontainerrepo:goazureporjectapi
        name: kiranbabycontainerreg
        ports:
          - containerPort: 8081
      imagePullSecrets: 
      - name: goazureporjectapisecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: goazureporjectapi-service
spec:
  type: LoadBalancer
  selector:
    name: goazureporjectapi
  ports:
  - name: http  
    port: 80
    targetPort: 8081
